### ISSUE TITLE
Session Json file not generated with profile env variable is set

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#329] opened 2019-03-29 15:36 UTC
I executed an experiment with 3100 pipelines and each pipeline has 2 stages and each stage 1 task. The `RADICAL_ENTK_PROFILE` variable is set to `TRUE` and the `*.prof` files from EnTK do have timestamps from my execution.

The log files do not contain any ERROR message.

**Comment by andre-merzky** [comment] 2019-04-09 21:52
need to reconfirm, the session writing has seen changes.

**Comment by mturilli** [comment] 2019-04-09 21:58
Unable to reproduce, closing until it pops up again.

**Closed by mturilli** 2019-04-09 21:58 UTC
Labels: layer:entk, priority:critical, type:bug
