### ISSUE TITLE
Setting up radical-entk on SUMMIT 

### ISSUE THREAD

**Issue by hengma1001** [radical-cybertools/radical.entk#355] opened 2019-06-05 21:15 UTC
I am trying to set up the radical.entk on Summit from OLCF. 

The testing code is modified version of `get_started.py` from examples running simply `echo Hello World`. I got the error of `radical.entk.exceptions.EnTKError: Cannot proceed. Resource allocation ended up in FAILED`. 

1. Here is the information from `radical-stack`. 
```
  python               : 2.7.15
  pythonpath           : /sw/summit/xalt/1.1.3/site:/sw/summit/xalt/1.1.3/libexec
  virtualenv           : entk

  radical.entk         : 0.7.16
  radical.pilot        : 0.60.1-v0.60.1-211-g5a062d6@fix-issue_1830
  radical.saga         : 0.60.0
  radical.utils        : 0.60.1
``` 

2. Error message (verbose). 
```
(entk) [hm0@login5.summit get_started]$ python get_started.py 
EnTK session: re.session.login5.hm0.018052.0003
Creating AppManager2019-06-05 16:53:15,043: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Application Manager initialized
                                                           ok
2019-06-05 16:53:16,029: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Created resource manager object: resource_manager.0000
Validating and assigning resource manager2019-06-05 16:53:16,030: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : DEBUG   : Validating resource description
2019-06-05 16:53:16,030: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Resource description validated
2019-06-05 16:53:16,030: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : DEBUG   : Populating resource manager object
2019-06-05 16:53:16,030: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : DEBUG   : Resource manager population successful
                                     ok
2019-06-05 16:53:16,030: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Workflow assigned to Application Manager
Setting up RabbitMQ system2019-06-05 16:53:16,030: radical.entk.appmanager.0000: MainProcess                     : MainThread     : DEBUG   : Setting up mq connection and channel
2019-06-05 16:53:16,056: radical.entk.appmanager.0000: MainProcess                     : MainThread     : DEBUG   : Connection and channel setup successful
2019-06-05 16:53:16,056: radical.entk.appmanager.0000: MainProcess                     : MainThread     : DEBUG   : Setting up all exchanges and queues
2019-06-05 16:53:16,084: radical.entk.appmanager.0000: MainProcess                     : MainThread     : DEBUG   : All exchanges and queues are setup
                                                    ok
2019-06-05 16:53:16,145: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    : Created WFProcessor object: wfprocessor.0000
2019-06-05 16:53:16,153: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Starting resource request submission
                                                                              ok
create pilot manager                                                          ok
submit 1 pilot(s)
        [ornl.summit:42]
        2019-06-05 16:53:22,500: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING_PENDING
                                                                      ok
2019-06-05 16:53:22,501: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Resource request submission successful.. waiting for pilot to go Active
2019-06-05 16:53:22,502: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING
2019-06-05 16:53:22,949: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: FAILED
2019-06-05 16:53:22,950: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2019-06-05 16:53:23,002: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Pilot is now active
2019-06-05 16:53:23,002: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager: Cannot proceed. Resource allocation ended up in FAILED
Traceback (most recent call last):
  File "/ccs/home/hm0/.conda/envs/entk/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 311, in run
    raise EnTKError(msg="Cannot proceed. Resource allocation ended up in %s"%res_alloc_state)
EnTKError: Cannot proceed. Resource allocation ended up in FAILED
2019-06-05 16:53:23,005: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2019-06-05 16:53:23,005: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : DEBUG   : WFprocessor process already terminated
wait for 1 pilot(s)
                                                                              ok
closing session re.session.login5.hm0.018052.0003                              \
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 9.5s                                                        ok
Traceback (most recent call last):
  File "get_started.py", line 70, in <module>
    appman.run()
  File "/ccs/home/hm0/.conda/envs/entk/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 311, in run
    raise EnTKError(msg="Cannot proceed. Resource allocation ended up in %s"%res_alloc_state)
radical.entk.exceptions.EnTKError: Cannot proceed. Resource allocation ended up in FAILED
```

3. Attached is the code. 
```python 
    # /gpfs/alpine/scratch/hm0/bip179/entk_test/get_started/get_started.py
    from radical.entk import Pipeline, Stage, Task, AppManager
    import os

    # ------------------------------------------------------------------------------
    # Set default verbosity

    if os.environ.get('RADICAL_ENTK_VERBOSE') == None:
        os.environ['RADICAL_ENTK_REPORT'] = 'True'

    # Description of how the RabbitMQ process is accessible
    # No need to change/set any variables if you installed RabbitMQ has a system
    # process. If you are running RabbitMQ under a docker container or another
    # VM, set "RMQ_HOSTNAME" and "RMQ_PORT" in the session where you are running
    # this script.
    hostname = os.environ.get('RMQ_HOSTNAME', 'csc190specfem.marble.ccs.ornl.gov')
    port = int(os.environ.get('RMQ_PORT', 30672))
    if __name__ == '__main__':

        # Create a Pipeline object
        p = Pipeline()

        # Create a Stage object
        s = Stage()

        # Create a Task object
        t = Task()
        t.name = 'my-first-task'        # Assign a name to the task (optional, do not use ',' or '_')
        t.executable = '/bin/echo'   # Assign executable to the task
        t.arguments = ['Hello World']  # Assign arguments for the task executable

        # Add Task to the Stage
        s.add_tasks(t)

        # Add Stage to the Pipeline
        p.add_stages(s)

        # Create Application Manager
        appman = AppManager(hostname=hostname, port=port)

        # Create a dictionary describe four mandatory keys:
        # resource, walltime, and cpus
        # resource is 'local.localhost' to execute locally
        res_dict = {
                'resource': 'ornl.summit',
                'project' : 'BIP179',
                'queue' : 'batch',
                'walltime': 10,
                'cpus': 42,
                # 'gpus': 18,
                'access_schema': 'local'
        }
        # Assign resource request description to the Application Manager
        appman.resource_desc = res_dict

        # Assign the workflow as a set or list of Pipelines to the Application Manager
        # Note: The list order is not guaranteed to be preserved
        appman.workflow = set([p])

        # Run the Application Manager
        appman.run()
```

Thank you very much.

**Comment by andre-merzky** [comment] 2019-06-05 21:43
Hi @hengma1001 , 

our support for summit is not yet complete and is not part of the released RCT modules.  As such, the resource acquisition will indeed fail on summit, and you would see the error above.  The release of summit support is planned for early August.  We might be possible to accommodate early users with limited functionality (and specifically limited scale) - let us know what your use case is and if you are interested. The pre-release versions are unlikely to work out of the box though.

**Comment by mturilli** [comment] 2019-06-05 23:03
Hi @andre-merzky, I asked @hengma1001 to open this ticket after a meeting we had today. This is related to the DeepMicroScope project, as per our internal documentation. We discussed the current limitations of our (unofficial) support of Summit, including the limited scale at which we an operate. This activity is related to a paper and has a fairly high priority. 

We should probably start by indicating the stack @hengma1001 should use to test his use case out. Note that, at the moment, we agreed to start with a toy workload. Upon success, we will try to move to the actual use case at scale <= 4 nodes.

**Comment by andre-merzky** [comment] 2019-06-06 06:21
Ah, I see - thanks for the context!

I need to check again if there is anything left to transfer into the RP code base (tests where done with lm_testing so far), and will ping back in a day or two.  Great, I'm looking forward to get some actual workloads onto summit :-D

**Comment by hengma1001** [comment] 2019-06-06 16:41
@mturilli, 
Thank you for explaining it. 

@andre-merzky, 
Thank you very much. The project is to run MD simulations managed by AI/ML. I will replace the toy workload with actual working case once I can get it running.

**Comment by mturilli** [comment] 2019-06-19 19:59
This is likely due to the RCT stack used on Summit. We are terminating our tests and merges and we should have a usable stack by the end of today.

**Comment by andre-merzky** [comment] 2019-06-20 13:44
All summit related capabilities are now in the devel branches of the RCT stack, and are scheduled for release on July 2nd.

**Comment by mturilli** [comment] 2019-06-21 18:12
An update: we tracked down the error and fixed it. We cannot fully test the fix as today Summit's shared FS is down but as soon as it will be available we should be able to release the fix.

**Comment by mturilli** [comment] 2019-06-25 00:04
Hi @hengma1001, here an update about your issue. We successfully fixed the problem you reported and run the proposed skeleton for your use case with null workload (https://github.com/radical-collaboration/hyperspace/blob/master/microscope/test_skeleton.py). You will have to install the full devel stack of RTC and then see whether the issue that you reported has been fixed for you too. If so, this ticket will be closed as addressed. Please let us know whether you need help with using the devel stack of RCT.

**Comment by mturilli** [comment] 2019-06-25 03:18
@hengma1001 and I tried to run `test_skeleton.py` on Summit Heng is using two.radical for mongdb, jetstream for RBMQ, and the following stack:

```
python               : 2.7.15
  pythonpath           : /sw/summit/xalt/1.1.3/site:/sw/summit/xalt/1.1.3/libexec
  virtualenv           : entk

  radical.entk         : 0.7.17-v0.7.17-37-g41835ea@devel
  radical.pilot        : 0.62.0-v0.62.0-314-gc79343a@devel
  radical.saga         : 0.62.0-v0.62.0-22-gc48ce13@devel
  radical.utils        : 0.62.0
```

We tried entk master/devel and coda/ve but Heng always get the following error:

```
(entk) [hm0@login4.summit microscope]$ python test_skeleton.py 
EnTK session: re.session.login4.hm0.018072.0007
Creating AppManager                                                           ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ systemTraceback (most recent call last):
  File "test_skeleton.py", line 173, in <module>
    appman.run()
  File "/ccs/home/hm0/.conda/envs/entk/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 470, in run
    self._terminate()
  File "/ccs/home/hm0/.conda/envs/entk/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 959, in _terminate
    write_session_description(self)
  File "/ccs/home/hm0/.conda/envs/entk/lib/python2.7/site-packages/radical/entk/utils/prof_utils.py", line 143, in write_session_description
    tree[amgr._uid]['children'].append(wfp._uid)
AttributeError: 'NoneType' object has no attribute '_uid'
```

We will resume testing tomorrow after 6pm.

**Comment by andre-merzky** [comment] 2019-06-25 05:07
Is RabbitMQ set up?

**Comment by mturilli** [comment] 2019-06-25 23:17
@hengma1001 was able to execute `test_skeleton.py` on Summit. This should address the issue of this ticket.

**Comment by lee212** [comment] 2019-09-05 04:15
The error message was seen by me as well when I set `RADICAL_ENTK_PROFILE=True`

**Comment by andre-merzky** [comment] 2019-09-05 05:51
@lee212 : which of the errors mentioned in the ticket: the `resource allocation failed` or `object has no _uid`?  For the former, either pilot submission failed which should leave traces in the `pmgr.0.launching.client.log` on the client side, or the pilot did not come up, which should leave some error messages in outputs or logs in the pilot sandbox.  If its the UID problem, I actually don't have any idea, yet.  Can you provide some script so I can try to reproduce it?  Thanks!

**Comment by lee212** [comment] 2019-09-05 15:30
It was for no `_uid` error but I think it is not caused by the env variable set (`RADICAL_ENTK_PROFILE`) that I mentioned earlier. It looked like my sandbox is no longer available on the scratch partition which I had change `default_remote_workdir` to suppress the error.

So, no, I can't reproduce the `no _uid` error.

**Comment by andre-merzky** [comment] 2019-09-05 15:34
Then I wouldn't mind ignoring the UID error until it pops up again and we have a reproducer...

**Comment by lee212** [comment] 2019-11-01 20:14
I assume this can be closed as it is no longer reproducible.

**Closed** 2019-11-01 20:14 UTC
Labels: layer:entk, layer:rp, priority:critical, topic:execution, topic:resource, type:question
