### ISSUE TITLE
pipeline suspend/resume problem

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#296] opened 2019-01-26 08:05 UTC
I use suspend/resume on EnTK pipelines.  The error I see is:

```
2019-01-26 08:55:55,296: radical.repex.exc   : wfprocessor                     : dequeue-thread : DEBUG   : === 0 no  - suspend
2019-01-26 08:55:55,316: radical.repex.exc   : wfprocessor                     : dequeue-thread : DEBUG   : === 1 check exchange : 1 >= 2?
2019-01-26 08:55:55,316: radical.repex.exc   : wfprocessor                     : dequeue-thread : DEBUG   : === 1 yes - exchange
2019-01-26 08:55:59,298: radical.repex.exc   : wfprocessor                     : dequeue-thread : DEBUG   : === 1 check resume
2019-01-26 08:55:59,298: radical.repex.rep   : wfprocessor                     : dequeue-thread : DEBUG   : === 0 add md
2019-01-26 08:55:59,298: radical.repex.exc   : wfprocessor                     : dequeue-thread : DEBUG   : === 0 resume (! 1)
2019-01-26 08:55:59,298: radical.repex.exc   : wfprocessor                     : dequeue-thread : ERROR   : === 0 resume failed
Traceback (most recent call last):
  File "../t.py", line 110, in _check_resume
    _replica.resume()
  File "/home/merzky/radical/radical.repex.sm/ve/local/lib/python2.7/site-packages/radical/entk/pipeline/pipeline.py", line 271, in resume
    'Cannot resume Pipeline %s since it is not suspended' % self._uid)
EnTKError: Cannot resume Pipeline pipeline.0000 since it is not suspended
```

Despite the error, I am positive that it is *this* pipeline (id `0`) which was suspended a couple of steps earlier (see the first log line in the output above).

Below is a script which reproduces this - it should not require any additional files to run.  Let me know if you want me to simplify this, and if you need additional information.

```py
#!/usr/bin/env python

import radical.entk  as re
import radical.utils as ru


# ------------------------------------------------------------------------------
#
def void():
    # entk needs callables as post_exec conditionals, even if there is nothing
    # to decide...
    pass


# ------------------------------------------------------------------------------
#
class Exchange(re.AppManager):

    def __init__(self, size, max_wait, min_cycles):

        self._size       = size
        self._max_wait   = max_wait
        self._min_cycles = min_cycles

        self._log = ru.Logger('radical.repex.exc')

        re.AppManager.__init__(self, autoterminate=False, port=5672) 
        self.resource_desc = {"resource" : 'local.localhost',
                              "walltime" : 30,
                              "cpus"     : 4}                                

        self._replicas  = list()
        self._waitlist  = list()

        # create the required number of replicas
        for i in range(size):

            replica = Replica(check_ex  = self._check_exchange,
                              check_res = self._check_resume,
                              rid       = i)

            self._replicas.append(replica)


        # run the replica pipelines
        self.workflow = set(self._replicas)
        self.run() 


    # --------------------------------------------------------------------------
    #
    def terminate(self):

        self._log.debug('exc term')

        # we are done!
        self.resource_terminate()


    # --------------------------------------------------------------------------
    #
    def _check_exchange(self, replica):

        self._log.debug('=== %s check exchange : %d >= %d?',
                  replica.rid, len(self._waitlist), self._max_wait)

        self._waitlist.append(replica)

        if len(self._waitlist) < self._max_wait:

            # just suspend this replica and wait for the next
            self._log.debug('=== %s no  - suspend', replica.rid)
            replica.suspend()

        else:
            # we are in for a wile ride!
            self._log.debug('=== %s yes - exchange', replica.rid)

            task = re.Task()
            task.name       = 'extsk'
            task.executable = 'date'

            stage = re.Stage()
            stage.add_tasks(task)
            stage.post_exec = {'condition': replica.check_resume,
                               'on_true'  : void,
                               'on_false' : void} 

            replica.add_stages(stage)


    # --------------------------------------------------------------------------
    #
    def _check_resume(self, replica):

        self._log.debug('=== %s check resume', replica.rid)

        # after a successfull exchange we revive all participating replicas.
        # For those replicas which did not yet reach min cycles, add an md
        # stage, all others we let die and add a new md stage for them.
        for _replica in self._waitlist:

            if _replica.cycle <= self._min_cycles:
                _replica.add_md_stage()

            # Make sure we don't resume the current replica
            if replica.rid != _replica.rid:
                self._log.debug('=== %s resume (! %s)',
                                _replica.rid, replica.rid)
                try:
                    _replica.resume()
                except:
                    self._log.exception('=== %s resume failed', _replica.rid)
                    import time
                    time.sleep(10)
                    raise

        # reset waitlist, increase exchange counter
        self._waitlist = list()


# ------------------------------------------------------------------------------
#
class Replica(re.Pipeline):
    '''
    A `Replica` is an EnTK pipeline which consists of alternating md and
    exchange stages.  The initial setup is for one MD stage - Exchange and more
    MD stages get added depending on runtime conditions.
    '''

    # --------------------------------------------------------------------------
    #
    def __init__(self, check_ex, check_res, rid):

        self._check_ex  = check_ex
        self._check_res = check_res
        self._rid       = rid

        self._cycle     = 0  # initial cycle

        re.Pipeline.__init__(self)
        self.name = 'p_%s' % self.rid
        self._log = ru.Logger('radical.repex.rep')

        # add an initial md stage
        self.add_md_stage()


    @property
    def rid(self):      return self._rid

    @property
    def cycle(self):    return self._cycle


    # --------------------------------------------------------------------------
    #
    def add_md_stage(self):

        self._log.debug('=== %s add md', self.rid)

        task = re.Task()
        task.name        = 'mdtsk-%s-%s' % (self.rid, self.cycle)
        task.executable  = 'date'

        stage = re.Stage()
        stage.add_tasks(task)
        stage.post_exec = {'condition': self.check_exchange,
                           'on_true'  : void,
                           'on_false' : void} 

        self.add_stages(stage)


    # --------------------------------------------------------------------------
    #
    def check_exchange(self):
        '''
        after an md cycle, record its completion and check for exchange
        '''

        self._cycle += 1
        self._check_ex(self)


    # --------------------------------------------------------------------------
    #
    def check_resume(self):
        '''
        after an ex cycle, trigger replica resumption
        '''
        self._check_res(self)


# ------------------------------------------------------------------------------
#
if __name__ == '__main__':

    exchange = Exchange(size=2, max_wait=2, min_cycles=4)
    exchange.terminate()

# ------------------------------------------------------------------------------

```

**Comment by vivek-bala** [comment] 2019-01-28 18:21
I can reproduce this and can confirm it is a bug. Working on this, I'll keep you posted. Will keep this high priority.

**Comment by vivek-bala** [comment] 2019-01-30 21:14
Hey Srinivas, I spent some time debugging this yesterday. I expect this to be fixed on Friday, after I spend some time tomorrow.

**Comment by vivek-bala** [comment] 2019-02-05 17:09
Hey Srinivas, please try https://github.com/radical-cybertools/radical.entk/tree/fix/issue_296 branch. I have incorporated the change for #298 as well. See the modified script below

```py
#!/usr/bin/env python

import radical.entk  as re
import radical.utils as ru


# ------------------------------------------------------------------------------
#
class Exchange(re.AppManager):

    def __init__(self, size, max_wait, min_cycles):

        self._size       = size
        self._max_wait   = max_wait
        self._min_cycles = min_cycles

        self._log = ru.Logger('radical.repex.exc')

        re.AppManager.__init__(self, autoterminate=False, hostname='two.radical-project.org',port=33251) 
        self.resource_desc = {"resource" : 'local.localhost',
                              "walltime" : 30,
                              "cpus"     : 4}                                

        self._replicas  = list()
        self._waitlist  = list()

        # create the required number of replicas
        for i in range(size):

            replica = Replica(check_ex  = self._check_exchange,
                              check_res = self._check_resume,
                              rid       = i)

            self._replicas.append(replica)


        # run the replica pipelines
        self.workflow = set(self._replicas)
        self.run() 


    # --------------------------------------------------------------------------
    #
    def terminate(self):

        self._log.debug('exc term')

        # we are done!
        self.resource_terminate()


    # --------------------------------------------------------------------------
    #
    def _check_exchange(self, replica):

        self._log.debug('=== %s check exchange : %d >= %d?',
                  replica.rid, len(self._waitlist), self._max_wait)

        self._waitlist.append(replica)

        if len(self._waitlist) < self._max_wait:
            # just suspend this replica and wait for the next
            self._log.debug('=== %s no  - suspend', replica.rid)
            replica.suspend()

        else:
            # self._waitlist = self._waitlist[:-1]

            # we are in for a wile ride!
            self._log.debug('=== %s yes - exchange', replica.rid)

            task = re.Task()
            task.name       = 'extsk'
            task.executable = 'date'

            stage = re.Stage()
            stage.add_tasks(task)
            stage.post_exec = replica.check_resume

            replica.add_stages(stage)


    # --------------------------------------------------------------------------
    #
    def _check_resume(self, replica):

        self._log.debug('=== %s check resume', replica.rid)

        # after a successfull exchange we revive all participating replicas.
        # For those replicas which did not yet reach min cycles, add an md
        # stage, all others we let die and add a new md stage for them.
        resumed_replicas = list()
        for _replica in self._waitlist:

            if _replica.cycle <= self._min_cycles:
                _replica.add_md_stage()

            # Make sure we don't resume the current replica
            if replica.rid != _replica.rid:
                self._log.debug('=== %s resume (! %s)',
                                _replica.rid, replica.rid)
                try:
                    self._log.debug('== Pipe %s trying to resume pipe %s in state %s'%(replica.uid, _replica.uid, _replica.state))
                    _replica.resume()
                    resumed_replicas.append(_replica.uid)
                    self._log.debug('== Pipe %s state ends up in %s'%(_replica.uid, _replica.state))
                except:
                    self._log.exception('=== %s resume failed', _replica.rid)
                    import time
                    time.sleep(10)
                    raise

        # reset waitlist, increase exchange counter
        self._waitlist = list()

        return resumed_replicas


# ------------------------------------------------------------------------------
#
class Replica(re.Pipeline):
    '''
    A `Replica` is an EnTK pipeline which consists of alternating md and
    exchange stages.  The initial setup is for one MD stage - Exchange and more
    MD stages get added depending on runtime conditions.
    '''

    # --------------------------------------------------------------------------
    #
    def __init__(self, check_ex, check_res, rid):

        self._check_ex  = check_ex
        self._check_res = check_res
        self._rid       = rid

        self._cycle     = 0  # initial cycle

        re.Pipeline.__init__(self)
        self.name = 'p_%s' % self.rid
        self._log = ru.Logger('radical.repex.rep')

        # add an initial md stage
        self.add_md_stage()


    @property
    def rid(self):      return self._rid

    @property
    def cycle(self):    return self._cycle


    # --------------------------------------------------------------------------
    #
    def add_md_stage(self):


        self._log.debug('=== %s add md', self.rid)

        task = re.Task()
        task.name        = 'mdtsk-%s-%s' % (self.rid, self.cycle)
        task.executable  = 'date'

        stage = re.Stage()
        stage.add_tasks(task)
        stage.post_exec = self.check_exchange

        self.add_stages(stage)


    # --------------------------------------------------------------------------
    #
    def check_exchange(self):
        '''
        after an md cycle, record its completion and check for exchange
        '''

        self._cycle += 1
        self._check_ex(self)


    # --------------------------------------------------------------------------
    #
    def check_resume(self):
        '''
        after an ex cycle, trigger replica resumption
        '''
        return self._check_res(self)


# ------------------------------------------------------------------------------
#
if __name__ == '__main__':

    exchange = Exchange(size=4, max_wait=4, min_cycles=4)
    exchange.terminate()

```

**Comment by mturilli** [comment] 2019-04-09 22:10
@SrinivasMushnoori Any update on this?

**Comment by vivek-bala** [comment] 2019-04-09 22:11
Vivek to test the suspend/resume with the repex example that Andre shared

**Comment by SrinivasMushnoori** [comment] 2019-04-09 22:45
I did do some testing, but that is so far inconclusive. Haven't been able to look at it since last Thursday unfortunately, buried in a proposal that is due tomorrow. Will prioritize this again starting tomorrow night.

**Comment by SrinivasMushnoori** [comment] 2019-04-12 19:42
Further testing has revealed that the pipelines do not suspend, but terminate. Give me about 20 minutes, will update this post with my script and such.

**Comment by SrinivasMushnoori** [comment] 2019-04-15 19:01
Sorry for the delay. Here's the relevant part of the terminal output: 

```
Update: p_3.stage.0002.mdtsk-3-0 state: DEQUEUEING
2019-04-15 14:23:24,860: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : INFO    : Transition of task.0002 to new state DEQUEUEING success
ful
2019-04-15 14:23:24,862: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0002 with state DEQUEUED
Update: p_3.stage.0002.mdtsk-3-0 state: DEQUEUED
2019-04-15 14:23:24,875: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : INFO    : Transition of task.0002 to new state DEQUEUED successfu
l
2019-04-15 14:23:24,878: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0002 with state DONE
Update: p_3.stage.0002.mdtsk-3-0 state: DONE
2019-04-15 14:23:24,879: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : INFO    : Transition of task.0002 to new state DONE successful
2019-04-15 14:23:24,881: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received stage.0002 with state DONE
2019-04-15 14:23:24,881: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found parent pipeline: pipeline.0002
Update: p_3.stage.0002 state: DONE
2019-04-15 14:23:24,882: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : INFO    : Transition of stage.0002 to new state DONE successful
2019-04-15 14:23:24,882: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : INFO    : Executing post-exec for stage stage.0002
waitlist is: 
2
1
3
sorted waitlist is: 
1
2
3
exchange size is  4  and exchange list length is  3
2019-04-15 14:23:24,883: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : INFO    : Post-exec executed for stage stage.0002
2019-04-15 14:23:24,891: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received pipeline.0002 with state DONE
2019-04-15 14:23:24,891: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found pipeline pipeline.0002, state DONE, completed 
False
2019-04-15 14:23:24,892: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Pipe pipeline.0002 completed
Update: 2019-04-15 14:23:24,892: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Active pipes: 1
p_3 state: DONE
2019-04-15 14:23:24,892: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : INFO    : Transition of pipeline.0002 to new state DONE successfu
l
2019-04-15 14:23:24,893: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : INFO    : Got finished task task.0003 from queue
2019-04-15 14:23:24,895: radical.entk.appmanager.0000: MainProcess   
```
What we see here is that the pipeline p_3 containing replica 3 should suspend, but it goes straight to te "done" state. [This](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_sliding_window.py#L212) is the script I'm using (with a few print statements commented in or out). 

Let me know if additional information is needed from me.

**Comment by andre-merzky** [comment] 2019-04-18 16:23
I updated the `async_repex` example in `fix/issue_296` and can confirm that suspend/resume is working.  The example is now expanded to handle multiple waitlists concurrently / asynchronously, and still works.  I consider this ticket closed.  

There remains the task to translate that functionality into the correct repex code, and we may consider to leave this ticket open until that happened.  The current change to move the sync process into a thread might also affect this functionality, and needs testing.  The updated example should be sufficient to do so.

The example writes, when running, a `dump.log` which traces the states for all replicas.  As long as that finishes with all replicas ending in `DONE` state (`=`), the test is considered successful.

**Comment by SrinivasMushnoori** [comment] 2019-04-18 16:28
@andre-merzky Question: so what state does a suspended pipeline display? 
`DONE` or `SUSPENDED` ?
Is there such a state as `SUSPENDED` ?

**Comment by SrinivasMushnoori** [comment] 2019-04-18 17:28
I can confirm that `fix/issue_296` is now working.
Yes I think we should leave this open until it is fully taken one layer up into RepEx.

**Comment by andre-merzky** [comment] 2019-04-18 22:58
> @andre-merzky Question: so what state does a suspended pipeline display?
> `DONE` or `SUSPENDED` ?
> Is there such a state as `SUSPENDED` ?

Yes, there is a `SUSPENDED` state, and that is what the pipeline transitions to.

**Comment by SrinivasMushnoori** [comment] 2019-04-18 23:04
Yes, as discussed in our call today, I can confirm. Thanks!

**Comment by mturilli** [comment] 2019-04-19 09:54
I think we should close this ticket as the original 'suspend/resume problem' has been fixed. @SrinivasMushnoori you will be able to open a new ticket if a new problem is found in EnTK while using this functionality in RepEx.

@andre-merzky, @vivek-bala this is a new functionality of EnTK so we should bump version to 0.8.0. I believe this should be done _before_ releasing the implementation of the sync process into a thread. If you agree, we will have pause/resume released on May 7 and sync into a thread on Jun 4.

**Comment by andre-merzky** [comment] 2019-04-19 21:02
Works for me.

**Closed** 2019-04-19 23:16 UTC
Labels: Replica Exchange, priority:high, topic:communication, type:bug
