### ISSUE TITLE
EnTK and runtime id mapping

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#500] opened 2020-11-03 22:40 UTC
EnTK should provide a mapping between its task ids and runtimes ids. Essentially, when the workflow is written as a json file. Currently, a workflow looks like:
```
'workflows': [{'pipes': [{'name': 'pipe.0000',
                          'stages': [{'name': 'stage.0000',
                                      'state_history': ['SCHEDULING'],
                                      'tasks': [{'name': 'task.0000',
                                                 'state': 'DESCRIBED',
                                                 'state_history': ['DESCRIBED'],
                                                 'uid': 'task.0000'}],
```

the feature ask for:

```
'workflows': [{'pipes': [{'name': 'pipe.0000',
                          'stages': [{'name': 'stage.0000',
                                      'state_history': ['SCHEDULING'],
                                      'tasks': [{'name': 'task.0000',
                                                 'state': 'DESCRIBED',
                                                 'state_history': ['DESCRIBED'],
                                                 'uid': 'task.0000',
                                                 'rts_id': 'uid.0000'}],
```

**Comment by iparask** [comment] 2020-11-03 22:40
@mturilli, is this according to our discussion?

**Comment by mturilli** [comment] 2020-11-06 18:24
Yes, I think that would be a way to address the mapping. We will then have to pick that value up in analytics and I think that should be relatively straightforward?

**Comment by andre-merzky** [comment] 2020-11-06 19:21
Hmm, the `tree` provided [here](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/utils/prof_utils.py#L131) should have all that information already, and that structure should already arrive in RA.  We should check why that is not used before implementing an additional way for the same information...

**Comment by iparask** [comment] 2020-11-06 19:36
The tree does not have all the information:
```
                    tree[stage._uid]['children'].append(task._uid)
                    tree[task._uid] = {'uid': task._uid,
                                       'etype': 'task',
                                       'cfg': {},
                                       'has': [],
                                       'children': list()
                                   }
```
We just need to add an entry there.

**Comment by andre-merzky** [comment] 2020-11-06 19:51
Hmm, the stage/task relation should be there (children is filled), but the following does indeed not work:
```py
#!/usr/bin/env python3

import sys
import pprint

import radical.analytics as ra

# ------------------------------------------------------------------------------
#
if __name__ == '__main__':

    session = ra.Session.create(sys.argv[1], 'radical.entk')
    print(session.describe('relations', etype=['pipeline', 'stage']))
```
results in 
```sh
inconsistent : no relations for pipeline.0000
{'pipeline.0000': []}
```
(this is after running `examples/simple/poe.py` on an up-ti-date stack)

**Comment by iparask** [comment] 2020-11-06 19:56
there is this [line](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/utils/prof_utils.py#L186) that creates the relationship you require.

As I understand it, the way the workflow is written is not compliant with RA. Let's try the following then: 
1. Workflow json being RA compliant
2. Introduce the new entry

@andre-merzky , @mturilli  what do you say?

**Comment by andre-merzky** [comment] 2020-11-06 21:56
I think it might be much simpler: it seems like RE needs to call `write_session_description(amgr)` before closing, and that actually creates that tree and stores it in the session dir, and `get_session_description` picks it up from there?

**Comment by andre-merzky** [comment] 2020-11-06 22:07
Yeah, once that is done, this all actually works:
```py
{'stage.0000': ['task.0000'], 'stage.0001': ['task.0007', 'task.0029', 'task.0008', 'task.0030', 'task.0009', 'task.0010', 'task.0011', 'task.0012', 'task.0013', 'task.0014', 'task.0015', 'task.0016', 'task.0017', 'task.0018', 'task.0019', 'task.0020', 'task.0021', 'task.0001', 'task.0022', 'task.0023', 'task.0002', 'task.0024', 'task.0003', 'task.0025', 'task.0004', 'task.0026', 'task.0005', 'task.0027', 'task.0006', 'task.0028'], 'stage.0002': ['task.0049', 'task.0050', 'task.0051', 'task.0031', 'task.0052', 'task.0053', 'task.0032', 'task.0054', 'task.0033', 'task.0055', 'task.0034', 'task.0056', 'task.0035', 'task.0057', 'task.0036', 'task.0058', 'task.0037', 'task.0059', 'task.0038', 'task.0060', 'task.0039', 'task.0040', 'task.0041', 'task.0042', 'task.0043', 'task.0044', 'task.0045', 'task.0046', 'task.0047', 'task.0048']}
```

**Comment by mturilli** [comment] 2020-11-06 22:23
I am not sure I follow your last comment. The problem is mapping tasks to unit right?

**Comment by andre-merzky** [comment] 2020-11-07 08:13
Ah, I am sorry, I was on the wrong track indeed then!  I tried to figure out the mapping from tasks to stages, stages to pipelines...
As for RE tasks to RP tasks: I would suggest to allow *setting* the RP task UID by RE, so that they share the same ID across the stack.  That is easy to implement, and will also help when integrating other systems with the same problem.

Another approach would be to add another input to RA, which would be a map of IDs which it should treat as synonyms.  That in turn would also help with, for example, PRTE and Flux integration, where we would just provide a map of backend UIDs to RP task UIDs and RA could then figure out how to sort through the respective profile entries.

Or both version really, neither is difficult to implement, both help integrated analysis (one upward, one downward).

**Comment by andre-merzky** [comment] 2020-11-07 08:32
The first approach is now implemented in radical-cybertools/radical.pilot/pull/2250 - happy to get feedback.

**Comment by iparask** [comment] 2020-11-18 14:43
As far as I remember, we said that RE will not change the UIDs from the runtime system is uses. Instead it will probe them and add them in the workflow json file. @andre-merzky that does not mean that the custom UID you've already implemented is not useful. Probably not for this.

@andre-merzky, @mturilli please correct me if I am not remembering correctly.

**Comment by andre-merzky** [comment] 2020-11-18 14:48
The custom UID has indeed somewhat different purposes.  

Can we maybe reopen the discussion though why we don't use the Task uid in RE as Task uid in RU?  That would not only make this part of the problem mute, but would also be intuitive for the users (like me for repex): when I have a task `task.0001`, I simply have a hard time finding out that I need to check sandbox `unit.0007` for it's output...

**Comment by iparask** [comment] 2020-11-18 15:15
We are still discussing about the mapping right? In the case of the mapping, we want to be independent of the runtime system we are using. RP may provide the capability to change the task id, but another may not. If we make the assumption, when writing the json file, that the runtime system task id is the same as EnTK's then we will not map correctly when the runtime system task id is different. As a result, the method that writes the workflow json file should use the ids offered by the runtime system.

Then there is the subject that you raise. I believe it is a bit different from the one of this ticket. You are discussing how EnTK uses a runtime system and whether or not changes the runtime system task id to EnTK's ids. I agree that if the runtime system offers that capability, we should use it. It will make our lives a bit easier. Also, if the runtime system allows to set the sandbox folder, EnTK should use the feature. 

Does this help? If it does not make sense let me know.  :)

**Comment by andre-merzky** [comment] 2020-11-18 15:18
That's all nice and well, but in practice, RP is currently the only runtime system to RE, and RA ID portability is only and issue with RP.  If another runtime system comes along, we likely have to find a different solution anyway - why should we address this now (and how)?  

I agree with the second part :-D

**Comment by iparask** [comment] 2020-11-18 15:55
RE knows the unit ids. We just have to add a key in the task entry, like the example in the first comment. This allows the json to be runtime independent, right? 


> That's all nice and well, but in practice, RP is currently the only runtime system to RE, and RA ID portability is only an issue with RP. If another runtime system comes along, we likely have to find a different solution anyway - why should we address this now (and how)?

I am not sure I understand, sorry. It is true that we are not addressing which runtime systems EnTK uses. We are discussing how to expand a utility function to include the IDs of the runtime system. Since EnTK knows the runtime system ids (it is how it gets information about the task's execution) why not write in the workflow json file? It is fast and clean and does not make any assumptions about the runtime system ids.

I'm sorry, but I do not understand why writing RP's unit ids to the workflow json file is such a problem?

**Comment by iparask** [comment] 2020-11-18 16:02
Now, there is a more important issue. There are two functions that write the workflows in json files. Those are [`write_workflow`](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/utils/prof_utils.py#L222) and [`write_session_description`](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/utils/prof_utils.py#L102). I suggest to remove one of the two functions.

I will probably keep the session description one.

**Comment by andre-merzky** [comment] 2020-11-18 20:58
Yeah, apologies, I should not be confusing the two issues.  There is no problem whatsoever with recording the IDs in the json files, and I don't mind if RE does not make assumptions about those IDs - so that's not a problem at all, and should be done.  I hoe that clarifies that part :-)

*Having said that*, the RCT stack will still be simpler to understand, and RA will be simpler to use and to code, if we keep task IDs consistent between RE and RP.  It probably has been discussed, but I at least cannot remember nor think of a reason not to do that.  

Why am I raising this here?  As stated in a comment above: if we need to map UIDs within the RCT stack, than that implies the need for additional code in RA which interprets that mapping.  I don't think that added code and complexity would be justified.

**Comment by iparask** [comment] 2020-11-18 21:01
> Yeah, apologies, I should not be confusing the two issues. There is no problem whatsoever with recording the IDs in the json files, and I don't mind if RE does not make assumptions about those IDs - so that's not a problem at all, and should be done. I hoe that clarifies that part :-)

Thank you, because I'm almost done!

> 
> _Having said that_, the RCT stack will still be simpler to understand, and RA will be simpler to use and to code, if we keep task IDs consistent between RE and RP. It probably has been discussed, but I at least cannot remember nor think of a reason not to do that.
> 
> Why am I raising this here? As stated in a comment above: if we need to map UIDs within the RCT stack, than that implies the need for additional code in RA which interprets that mapping. I don't think that added code and complexity would be justified.

Let me suggest that I open a feature request and implement the custom RP ID in EnTK when RP's PR is merged with devel. Do you agree?

**Comment by andre-merzky** [comment] 2020-11-18 21:13
> Thank you, because I'm almost done!
:-)

> Let me suggest that I open a feature request and implement the custom RP ID in EnTK when RP's PR is merged with devel. Do you agree?

Sure!

**Closed** 2020-11-19 20:29 UTC
Labels: layer:entk, type:feature
