### ISSUE TITLE
requesting CPU cores for python multiprocessing package

### ISSUE THREAD

**Issue by igory1999** [radical-cybertools/radical.entk#537] opened 2021-01-25 14:46 UTC
I am trying to use python multiprocessing package.

Inside the program, I have a pool that is created and destroyed in a loop:

```
from multiprocessing import Pool

def write_pdb(...):
   ...

while(True):
  ...
  with Pool(40) as p:
        p.map(write_pdb, outlier_list_uni)
  ...
```

When requesting resources from ENTK, I do the following:
```
t4.cpu_reqs = {'processes': 1,
                          'process_type': None,
               'threads_per_process': 40,
               'thread_type': 'OpenMP'
               }
```
Running top on the compute node, shows that 40 processes are executed on my smaller number of CPU cores, probably 1.
(Is there a way to add an attachment with a screenshot? At first glance I do not see how)

Should the resources be requested differently for this situation? Perhaps, 'processes': 40, threads_per_process':1?

**Comment by iparask** [comment] 2021-01-25 16:27
Hello @igory1999, since you are creating processes and not threads, I would suggest you request 40 processes with one thread per process.

**Comment by iparask** [comment] 2021-02-03 16:52
Hello @igory1999, is this still an issue?

**Comment by igory1999** [comment] 2021-02-03 17:48
Yes.
In simple standalone program multiprocessing works fine in combination with
entk, but in the real program it seems to be running on a single or too
small number of cores.
I'll try to isolate the problem.  Currently I don't have a small
reproducible example.

**Comment by iparask** [comment] 2021-03-30 20:17
Hello @igory1999, I'm going to close this. Please feel free to reopen it when you have a reproducible example

**Closed by iparask** 2021-03-30 20:17 UTC
Labels: layer:entk, topic:execution, type:question
