### ISSUE TITLE
more than 68 cpus cannot be utilized on stampede2

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.entk#416] opened 2020-01-30 04:01 UTC
Hello,
I encountered an issue while running a set of scripts on xsede.stampede2. Briefly, any script fails to complete execution if the number of cpus is set to a number greater than 68. As an example, below are the log files for get_started.py sample script where the number of cpus is set to 69 (see res_dict from the sample script). 

Since a stampede2 node is with 68 cores, the error may be due to do failure of assigning more than one node for my entire workload. As it can be seen in the verbose.log file, it prints the following error:
`radical.entk.exceptions.EnTKError: Cannot proceed. Resource ended in state FAILED`

```
    res_dict = {
        'resource': 'xsede.stampede2_ssh',
        'walltime': 10,
        'cpus': 69,
        'project': 'TG-MCB090174',
        'schema': 'gsissh'
    }

```

```
radical-stack:
  python               : 3.7.6
  pythonpath           :
  virtualenv           : /home/aydins/ve-entk

  radical.analytics    : 0.90.7-v0.72.0-35-g4f5242d@devel
  radical.entk         : 1.0.0
  radical.pilot        : 1.0.0
  radical.saga         : 1.0.1
  radical.utils        : 1.0.0
```

[sessionlogs.zip](https://github.com/radical-cybertools/radical.entk/files/4132066/sessionlogs.zip)
[verboselog.zip](https://github.com/radical-cybertools/radical.entk/files/4132067/verboselog.zip)

**Comment by mturilli** [comment] 2020-02-04 19:37
Confirmed, see https://github.com/radical-cybertools/radical.pilot/issues/2058

**Comment by lee212** [comment] 2020-02-04 20:16
I believe this issue on entk can be closed to reduce duplication.

**Comment by mturilli** [comment] 2020-02-04 22:13
In the past, when the issue turns out to be in another RCT, we referenced all the tickets and kept the issue open until it was addressed. The idea is that the end user knows only about this ticket and wants to know when the issue s|he has reported is addressed by looking at this ticket. Do you think it makes sense?

**Comment by lee212** [comment] 2020-02-04 22:32
Yes, it does make sense. Duplicate of radical-cybertools/radical.pilot#2058 for cross reference.

**Comment by lee212** [comment] 2020-02-04 22:36
Duplicate of radical-cybertools/radical.pilot#2058

**Comment by lee212** [comment] 2020-07-07 19:39
It seems this has been resolved. Closing now.

**Closed by lee212** 2020-07-07 19:39 UTC
Labels: layer:entk, type:bug
