### ISSUE TITLE
None directory in sandbox

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.entk#424] opened 2020-02-13 23:23 UTC
updated my radical-stack and now in sandbox session I don't see all units, only one "None" directory where the 0th task is working as expected. All other tasks fail. Get_started example works but gives None directory too. Maybe get_started works only because it has one task, more will fail.

sandbox session(120MB):
https://drive.google.com/file/d/1uWu1_1Xoaj6ug1gY0eQpGLe3S4opBs-f/view?usp=sharing
radical-stack
```
  python               : 3.7.6
  pythonpath           : /sw/summit/xalt/1.2.0/site:/sw/summit/xalt/1.2.0/libexec
  virtualenv           : vampnet

  radical.entk         : 1.0.0-v1.0.0-13-g2b6350b@devel
  radical.pilot        : 1.1.0-v1.1@devel
  radical.saga         : 1.1.0-v1.1@devel
  radical.utils        : 1.1.1-v1.1.1-2-gfe6c424@devel
```

**Comment by andre-merzky** [comment] 2020-02-14 01:12
This is fixed in the last release of RP.  Please note that updating RP also requires updating RU.

**Comment by euhruska** [comment] 2020-02-14 03:31
updated RP to 1.1.1 but still see same "None" directory
```
  radical.analytics    : 0.90.7-v0.72.0-38-g14b9581@devel
  radical.entk         : 1.0.1-v1.0.1@devel
  radical.pilot        : 1.1.1-v1.1.1@devel
  radical.saga         : 1.1.0-v1.1@devel
  radical.utils        : 1.1.1-v1.1.1-2-gfe6c424@devel
```

**Comment by andre-merzky** [comment] 2020-02-14 09:32
Oh, I expected this to be a duplicate of radical-cybertools/radical.pilot/issues/2053 ...  

Thanks for providing the pilot sandbox.  Despite the `None` problem (which is a bug), the run actually failed because python segfaulted (you have a 3.3 GB core dump in `None/` which indicates this).  The task should run despite the incorrect sandbox name.  I am not sure what triggered the python problem - your module load pre-execs seemed to work as expected.  You seem to load the gcc module though *after* activating the conda env - not sure if that may create issues?  I would suggest to first load all modules and then to activate.

As for the `None/`: I don't understand really where this comes from: the stack you use includes the fix for the above mentioned RP issue (I checked twice).  Can you please also provide the client sandbox?  The incorrect path is determined at the client side before the unit is transferred to the pilot.  Thanks!

**Comment by euhruska** [comment] 2020-02-14 16:09
Thank for letting me know about the env
Here the local session
[re.session.login1.eh22.018305.0022.zip](https://github.com/radical-cybertools/radical.entk/files/4205312/re.session.login1.eh22.018305.0022.zip)

**Closed** 2020-02-18 16:28 UTC
Labels: layer:entk, layer:rp, priority:critical, type:bug

**Comment by lee212** [comment] 2020-02-18 16:29
@euhruska, This is automatically closed by GitHub but if you see that the problem persists, feel free to reopen the issue.

**Comment by euhruska** [comment] 2020-02-18 17:41
yes, fixed
