### ISSUE TITLE
 full path of $SHARED

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.entk#259] opened 2018-08-08 20:35 UTC
Is there a function in entk giving the full path of $SHARED? I want to use that path in a unit to work with the data. The alternative would be to copy/link stuff to a unit and then do a quick step and the copy all back to $SHARED, which usually makes sense but not for this quick step and lots of data.

**Comment by vivek-bala** [comment] 2018-08-09 02:57
Do you mean you want to use $SHARED as an argument to an executable? $SHARED is currently only parsed in the staging directives.

**Comment by euhruska** [comment] 2018-08-09 14:17
No, just having a function/command which gives me the full path of $SHARED

**Comment by vivek-bala** [comment] 2018-08-14 16:38
There is no command that provides it. But I suppose you want to use that full path as an argument to the executable of a task. Is that correct?

**Comment by euhruska** [comment] 2018-08-14 16:43
yes, that is correct. That way the executable can access the files in $SHARED directly

**Comment by vivek-bala** [comment] 2018-08-14 16:48
Ok, I will parse the arguments to also expand $SHARED appropriately and the user can simply use $SHARED in both the arguments as well as the staging directives. Does that fit your requirements?

**Comment by vivek-bala** [comment] 2018-09-06 22:28
Moving this to the next milestone as it requires more discussion

**Comment by SrinivasMushnoori** [comment] 2018-10-03 11:33
@vivek-bala is this feature present in the latest master?

**Comment by andre-merzky** [comment] 2018-10-08 14:07
@vivek-bala : is that `$SHARED` the pilot's staging area, or is that some EnTK specific location?  If the former, we can expose it as `$RP_PILOT_STAGING` env variable (we already expose a number of `RP_*` variables to the units).

**Comment by SrinivasMushnoori** [comment] 2018-10-12 14:49
Has there been movement on this?
Thanks.

**Comment by vivek-bala** [comment] 2018-10-12 20:15
@andre-merzky It is indeed the pilot staging area. I think the env variable would work.

**Comment by andre-merzky** [comment] 2018-10-12 21:41
Then let me provide this.

**Comment by andre-merzky** [comment] 2018-10-12 22:03
You can give the RP branch `feature/entk_259` a try...

**Comment by SrinivasMushnoori** [comment] 2018-10-15 22:00
I have just tested this, but it failed. Here's what happened:

-The full EnTK script is [here](https://github.com/radical-cybertools/radical.entk/files/2480684/driver.py.tar.gz), see lines 114-121

- My task's arguments are as follows:

```
md_tsk.arguments = ['-O', 
                            '-i', 'mdin-{replica}-{cycle}'.format(replica=rid, cycle=0), 
                            '-p', 'prmtop', 
                            '-c', 'inpcrd', 
                            '-o', 'out',
                            '-r', '%s/restrt-{replica}-{cycle}'.format(replica=rid, cycle=cycle)%init_sandbox,
                            '-x', 'mdcrd',
                            '-inf', '%s/mdinfo-{replica}-{cycle}'.format(replica=rid, cycle=cycle)%init_sandbox]
```

- The first argument is a `-O` which tells the executable to overwrite any pre-existing output files. 
- Line 6 is an MD output file that is written to the `init_sandbox` which is basically a variable that holds the placeholder name for the VERY first task of this end to end workflow.
- Line 8 is another MD output file that is also written to the same location. 
- The workflow executes, but the MD tasks fail. Digging into the MD task sandboxes I see the following in the `STDERR` file:
```
  Error opening unit    7: File "/mdinfo-0-1" exists (use -O to overwrite)     
```
- Now there are a couple of issues here, first, it seems to be writing to some kind of "root" directory, and not the `init_sandbox` . Second, it says "use -O to overwrite" when there already is a -O in the arguments. 
- In the .sh file of the unit sandbox, the execute command looks like:
```
/home/scm177/mantel/AMBER/amber14/bin/sander "-O" "-i" "mdin-0-0" "-p" "prmtop" "-c" "inpcrd" "-o" "out" "-O" "-r" "$Pipeline_untarPipe_Stage_untarStg_Task_untarTsk/restrt-0-1" "-x" "mdcrd" "-O" "-inf" "$Pipeline_untarPipe_Stage_untarStg_Task_untarTsk/mdinfo-0-1"
```
- According to this line, the -O option appears to have been parsed. Similarly, the placeholder name for the location of the `init_sandbox` has also been parsed. However, the `STDERR` appears to attempt to write to some kind of root directory, not the unit sandbox of the first task.
- This has been reproduced by attempting to write to $SHARED as well.

**Comment by SrinivasMushnoori** [comment] 2018-10-15 22:16
Further testing:

I set up a pre_exec as follows to see exactly where the placeholder points to
```
md_tsk.pre_exec   = ['export dummy_variable=19', 'echo $Pipeline_untarPipe_Stage_untarStg_Task_untarTsk >> test.file']
```

test.file is an empty file that is somehow 1 byte in size.

**Comment by vivek-bala** [comment] 2018-10-16 12:09
Thanks for testing Srinivas. This is fixed in 0.7.8 (hotfix) that I just released. Also tested with an integration test at https://github.com/radical-cybertools/radical.entk/blob/master/tests/test_issues/test_issue_259.py.

Note that we only parse the arguments and staging attributes, not pre_exec (or any other attribute).

**Comment by andre-merzky** [comment] 2018-10-16 15:33
In the referenced RP branch, the variable is named `RP_PILOT_SBOX`.

**Comment by SrinivasMushnoori** [comment] 2018-10-16 15:37
I see, thanks for letting me know. I'll give `$RP_PILOT_SBOX` a shot as well, but either method is a perfectly workable solution. The latter is *slightly* messy because some non-replica files are also present in the unit sandbox that acts as the replica sandbox, so perhaps  `$RP_PILOT_SBOX` is a cleaner way to do it. Thanks!

**Comment by vivek-bala** [comment] 2018-10-16 16:32
Ok, so ``RP_PILOT_SBOX`` refers to the shared staging area? Why was this changed from ``$RP_PILOT_STAGING``?

@SrinivasMushnoori  Can you help me understand what your former and latter methods are please? I believe we agreed on parsing $SHARED and $Pipeline_*_Stage_*_Task_* in the arguments similar to how it is done in the staging directives.

**Comment by SrinivasMushnoori** [comment] 2018-10-16 16:40
@vivek-bala yes we did. 

Former method (let's call it method M1) is to specify `$SHARED/restrt-{replica}-{cycle}'.format(replica=rid, cycle=cycle)` in the arguments. 

Latter method (M2) is to specify `'%s/restrt-{replica}-{cycle}'.format(replica=rid, cycle=cycle)%init_sandbox` in the arguments. 

They are both _functionally_ identical as far as my application is concerned: all simulation outputs are written to ONE directory. I'm using M2 method as of now, since M1 still fails with the following error:

```
  Error opening unit    7: File "/mdinfo-0-1" exists (use -O to overwrite)  
```
Perhaps because the placeholder name changed from `$SHARED` to `$RP_PILOT_SBOX`?
I tried using `$RP_PILOT_SBOX` as well but EnTK throws an error that the placeholder length is incorrect, presumably due to the presence of underscores (I believe, Vivek, you and I have run into this issue before). 

Does that clarify?

**Comment by vivek-bala** [comment] 2018-10-16 16:56
Ah okay. Let's see if the following clarifies the issue. The way you refer to the placeholders is correct:
```
t.arguments = ['{placeholder}/restrt-{replica}-{cycle}'.format(replica=rid, cycle=cycle, placeholder=x)
```

'x' here can be ``$SHARED`` to refer to the shared staging area within each RP run or ``$Pipeline_*_Stage_*_Task_*`` if you want to refer to a specific task. Both of them are internally translated to the correct path. You, the user, do not have to use any other type of placeholder.

If you want to use $SHARED, however, you need to use the branch that Andre created in RP (feature/entk_259). Internally, EnTK translates $SHARED to $RP_PILOT_STAGING and lets RP take over specifying the staging area's path. Does that help clarify? 

What I don't understand right now is what ``RP_PILOT_SBOX`` refers to? @andre-merzky

**Comment by SrinivasMushnoori** [comment] 2018-10-16 16:59
I see, that makes sense. However I'll not use `RP_PILOT_SBOX` yet while you and @andre-merzky 
suss out the details about where exactly it points to. Once there is clarity on that, let me know and I'd be happy to test on my end.

**Comment by andre-merzky** [comment] 2018-10-16 18:04
> Ok, so `RP_PILOT_SBOX` refers to the shared staging area? Why was this changed from `$RP_PILOT_STAGING`?

@vivek-bala : Oh bugger, you are right,  that was supposed to be `RP_PILOT_STAGING`!  I'll fix that immediately.  It *is* pointing to the staging area, not the pilot sandbox...

**Comment by andre-merzky** [comment] 2018-10-16 18:06
The change is now pushed to RP's `feature/entk_259` branch.

**Comment by vivek-bala** [comment] 2018-11-12 16:10
Closing this as old. Based on conversations, this seems to have been fixed in the latest releases.

**Closed by vivek-bala** 2018-11-12 16:10 UTC
Labels: topic:api, type:enhancement
